### ISSUE TITLE
Simple spec about with-config functions cannot be proven

### ISSUE THREAD

**Issue by ehildenb** [kframework/kore#1324]
This is in support of Polkadot project.

Here is the definition (which uses a with-config/contextual function):

```
module SET-BALANCE 
    imports INT 
    imports DOMAINS 
    imports COLLECTIONS 
 
    configuration 
      <set-balance> 
        <k> $PGM:Int </k> 
        <accounts> 
          <account multiplicity="*" type="Map"> 
            <accountID> .AccountId:AccountId </accountID> 
            <freeBalance> 0 </freeBalance> 
          </account> 
        </accounts> 
      </set-balance> 
 
    syntax AccountId ::= ".AccountId" | Int 
 // --------------------------------------- 
 
    syntax Int ::= "total_balance" "(" AccountId ")" [function, functional] 
 // ----------------------------------------------------------------------- 
    rule total_balance(WHO) => 0 [owise] 
    rule [[ total_balance(WHO) => FREE_BALANCE ]] 
         <account> 
           <accountID> WHO </accountID> 
           <freeBalance> FREE_BALANCE </freeBalance> 
         </account> 
endmodule 
```

And here is the specification (that fails to prove):

```
requires "set-balance.k" 
 
module VERIFICATION 
    imports SET-BALANCE 
endmodule 
 
module SET-BALANCE-SPEC 
    imports VERIFICATION 
 
    rule <k> total_balance(AID) => 30 </k> 
         <accounts> 
           <account> 
             <accountID> AID </accountID> 
             <freeBalance> 30 </freeBalance> 
           </account> 
         </accounts> 
endmodule 
```

The output given is:

```
  #Not ( #Exists _2 . #Exists _3 . #Ceil ( <account>
      <accountID>
        AID
      </accountID>
      <freeBalance>
        _2
      </freeBalance>
    </account> _3 )
  #And
    {
      _Configuration1
    #Equals
      <account>
        <accountID>
          AID
        </accountID>
        <freeBalance>
          _2
        </freeBalance>
      </account> _3
    } )
#And
  <set-balance>
    <k>
      0
    </k>
    <accounts>
      <account>
        <accountID>
          AID
        </accountID>
        <freeBalance>
          30
        </freeBalance>
      </account>
    </accounts>
  </set-balance>
```

Which indicates to me that the Haskell backend cannot prove that only the non-`owise` case of the `total_balance` function is actually feasible.

**Comment by ttuegel** [comment]
> Which indicates to me that the Haskell backend cannot prove that only the non-`owise` case of the `total_balance` function is actually feasible.

This actually seems to indicate that the backend cannot prove the `owise` case is *in*feasible. This would be fixed by #1318.

**Comment by ehildenb** [comment]
Without the `owise` rule, we get this error message instead:

```
  #Ceil ( total_balance ( AID ) <set-balance>
    <k>
      _Configuration2
    </k>
    <accounts>
      _Configuration1
    </accounts>
  </set-balance> )
#And
  #Not ( #Ceil ( total_balance ( AID ) <set-balance>
      <k>
        _Configuration2
      </k>
      <accounts>
        _Configuration1
      </accounts>
    </set-balance> )
  #And
    {
      30
    #Equals
      total_balance ( AID ) <set-balance>
        <k>
          _Configuration2
        </k>
        <accounts>
          _Configuration1
        </accounts>
      </set-balance>
    } )
#And
  <set-balance>
    <k>
      total_balance ( AID ) <set-balance>
        <k>
          _Configuration2
        </k>
        <accounts>
          _Configuration1
        </accounts>
      </set-balance>
    </k>
    <accounts>
      <account>
        <accountID>
          AID
        </accountID>
        <freeBalance>
          30
        </freeBalance>
      </account>
    </accounts>
  </set-balance>

```

**Comment by ehildenb** [comment]
These are tarballs, name has `.txt` to appease GitHub.

I just included the generated `.kprove...` directory when run with `--debug` for each case.

[without-owise.tar.txt](https://github.com/kframework/kore/files/3928244/without-owise.tar.txt)
[with-owise.tar.txt](https://github.com/kframework/kore/files/3928245/with-owise.tar.txt)

**Comment by virgil-serbanuta** [comment]
The problem is that the translation to kore is broken, and I couldn't figure out how to translate it properly. I'll post a more detailed description on #kore, but here's why this does not work:

The axiom is translated to
```
axiom{R}
  \implies{R} (
    \top{R}(),
    \and{R} (
      \equals{SortInt{},R} (
        total_balance(_)_WITH-CONFIG_Int_AccountId{}(
          VarWHO:SortAccountId{},
          \and{SortGeneratedTopCell{}}(
            <generatedTop>{}(
              <set-balance>{}(
                VarDotVar1:SortKCell{},
                <accounts>{}(
                  _AccountCellMap_{}(
                    AccountCellMapItem{}(
                      <accountID>{}(VarWHO:SortAccountId{}),
                      <account>{}(
                        <accountID>{}(VarWHO:SortAccountId{}),
                        <freeBalance>{}(VarFREE_BALANCE:SortInt{})
                      )
                    ),
                    VarDotVar2:SortAccountCellMap{}
                  )
                )
              ),
              VarDotVar0:SortGeneratedCounterCell{}
            ),
            Var_Configuration:SortGeneratedTopCell{}
          )
        ),
        VarFREE_BALANCE:SortInt{}
      ),
      \top{R}()
    )
  )
```

where `Var_Configuration:SortGeneratedTopCell{}` is a free variable, not related in any way to the configuration. 

For anyone that still needs to be convinced, this is as wrong as it gets: the free variable is (implicitly) quantified universally, and for most of the possible values the `and` including it will be evaluated to bottom, which means that the first term of the equality will be bottom most of the time. The second term of the equality is a variable, which can't be bottom, which means that for most values of `Var_Configuration` the entire equality will be bottom. Since the variable is quantified universally, the entire axiom is bottom.

**Comment by virgil-serbanuta** [comment]
Discussion started here:
https://runtimeverification.slack.com/archives/CFGK6NJMU/p1576093355029000

Besides what I said there, we're also passing a free variable without any constraint (`Var_Configuration`) to the `total_balance` function in the initial configuration.

**Comment by ehildenb** [comment]
This seems at first glance like a naive encoding of `#as` patterns?

A function like:

```
    syntax Int ::= "total_balance" "(" AccountId ")" [function, functional] 
 // ----------------------------------------------------------------------- 
    rule total_balance(WHO) => 0 [owise] 
    rule [[ total_balance(WHO) => FREE_BALANCE ]] 
         <account> 
           <accountID> WHO </accountID> 
           <freeBalance> FREE_BALANCE </freeBalance> 
         </account> 
```

Should be roughly translated to:

```
    syntax Int ::= "total_balance" "(" AccountId ")" [function, functional] 
           | "total_balance(_)_WITH-CONFIG_Int_AccountID" "(" AccountId "," GeneratedTopCell ")"
```

Where then then the rules are added:

```
rule <generatedTopCell> ... total_balance(WHO) ... </generatedTopCell> #as Var_Configuration
    => total_balance(_)_WITH-CONFIG_Int_AccountId(WHO, Var_Configuration)

rule total_balance(_)_WITH-CONFIG_Int_AccountId(_, _) => 0 [owise]
rule total_balance(_)_WITH-CONFIG_Int_AccountId(WHO,
         <generatedTopCell>
         ...
         <account> 
           <accountID> WHO </accountID> 
           <freeBalance> FREE_BALANCE </freeBalance> 
         </account> 
         ...
       </generatedTopCell>)
    => FREE_BALANCE
```

I admit, I have no idea how the first rule would be translated, but this is my rough understanding of what's going on.

So what looks like what's happening to me is that the encoding of the `#as` pattern in the first rule would lead to the conjunct between `<generatedTopCell>` and `Var_Configuration` showing up. Maybe the encoding has some weirdness about it, or could be improved.

Pinging @dwightguth for more understanding of what the frontend is doing here.

**Comment by ttuegel** [comment]
This rule is problematic:

```
rule <generatedTopCell> ... total_balance(WHO) ... </generatedTopCell> #as Var_Configuration
    => total_balance(_)_WITH-CONFIG_Int_AccountId(WHO, Var_Configuration)
```

1. `total_balance(WHO)` can appear anywhere in the configuration.
1. ` total_balance(_)_WITH-CONFIG_Int_AccountId(WHO, Var_Configuration)` must put the result back in the same place in the configuration.

**Comment by ehildenb** [comment]
@ttuegel what happens in the RHS of the other rules in the file are analyzed to determine the locations these functions can show up. So if you had:

```
rule <k> foo(WHO) => total_balance(WHO) ... </k>
```

It will produce:

```
rule <k> foo(WHO) ~> REST </k> #as Var_Configuration => <k> total_balance(_)_WITH-CONFIG_Int_AccountId(WHO, Var_Configuration) ~> REST </k>
```

**Comment by ehildenb** [comment]
And actually, looking at the generated Kore, it seems that the production `total_balance(_)` is dropped altogether from the definition, only the `total_balance(_)_WITH-CONFIG_Int_AccountId` production is kept.

**Comment by virgil-serbanuta** [comment]
Here's the current description of the problem as I currently understand it (thanks, @traiansf , for explaining most of this to me).

1. The current encoding of equality rules using `#as` is broken. To be precise, `f(thing as #x)=stuff` is ecoded as `f(and(thing,x))=stuff` which, as explained above, is wrong. A possible way around this is: `f(x)=stuff requires ceil(and(thing,x))`. Fixing this requires a frontend change.

2. As described here: https://github.com/kframework/k/blob/master/pending-documentation.md#matching-global-context-in-function-rules , the configuration used by `foo` is the _previous_ configuration (rather counterintuitive IMO, but works around many issues). However, this means that it makes no sense to use a function with context in the left hand side of a claim, as is the case above.

**Comment by ttuegel** [comment]
> The current encoding of equality rules using `#as` is broken.

Oh, good grief, another frontend soundness bug. I will open an issue upstream, but I am increasingly inclined to say that encoding functions as equations is _wrong_.

> [I]t makes no sense to use a function with context in the left hand side of a claim, as is the case above.

@virgil-serbanuta I don't understand this part. The documentation you linked shows a desugared rule where the function receives the configuration on the left-hand side of the desugared rule. I don't see why that would cause a problem with claims.

**Comment by virgil-serbanuta** [comment]
Ok, maybe that wasn't fully correct. Here's a more nuanced opinion:

If I understand that correctly, the context is supposed to work like this: when evaluating `foo`, we use the context from the previous step. I.e. if we transition from `A` to `B` where `B` is `foo(???)`, then `B` should be `foo(A)`. So, when writing `foo(???) => C` we can only fill `???` with something if we assume that there was a previous step. Is that a reasonable assumption? I assumed that it isn't, but it probably is.

However, since we don't know the previous configuration, and the user can't provide hints in the claim, then the obvious option is to put a variable there, and that's what the frontend does now. This means that the rule must work for all possible previous configurations, although the claim LHS usually can follow only from a relatively small subset of configurations, and probably uniquely identifies all the data needed to actually evaluate `foo`. But we can't use because there are no constraints on that variable.

**Comment by virgil-serbanuta** [comment]
For a while, the branch below will contain a test for a with-config function that shows up in a subsequent step:

https://github.com/virgil-serbanuta/kore/tree/with-config

**Comment by ehildenb** [comment]
@virgil-serbanuta Tom made me aware of the issue with using a contextual function in the LHS of a claim, your fix in the above regression test looks reasonable to me, and is what I would have suggested anyway.

**Comment by virgil-serbanuta** [comment]
Ok, hopefully it will work after https://github.com/kframework/k/issues/975 is fixed and I'll be able to merge that branch.

**Comment by virgil-serbanuta** [comment]
@ehildenb I just merged https://github.com/kframework/kore/pull/1352 , I think this fixes the issue you were seeing, so I'll close this issue. Please reopen if that's not the case.

**Comment by ehildenb** [comment]
Well, I still can't prove this specification, so I guess it's not fixed.

**Comment by virgil-serbanuta** [comment]
A few questions:

1. Are you trying to prove the specification as written above? If yes, as discussed [above](https://github.com/kframework/kore/issues/1324#issuecomment-565473459), it should not work (because there is no previous configuration, as required by with-config function, so the frontend is actually using a generic configuration in this rule, i.e. an unconstrained configuration variable; we can't lookup specific accounts in a variable, and, even if we did, we wouldn't get the expected result).

2. If not, could you give me the new spec? I assume my definition is identical to yours:
https://github.com/kframework/kore/blob/master/src/main/k/working/tests/with-config/with-config.k

FWIW, my spec contains the simplest fix that would make it work:
https://github.com/kframework/kore/blob/master/src/main/k/working/tests/with-config/prove/one-spec.k

**Comment by ehildenb** [comment]
You're right, I forgot to add the extra initilizaition step, this spec works:

```
requires "set-balance.k" 
 
module VERIFICATION 
    imports SET-BALANCE 
 
    syntax EntryAction ::= totalBalance ( AccountId ) 
    rule <k> totalBalance(AID) => total_balance(AID) ... </k> 
endmodule 
 
module SET-BALANCE-SPEC 
    imports VERIFICATION 
 
    rule <k> totalBalance(AID) => 50 ... </k> 
         <accounts> 
           <account> 
             <accountID> AID </accountID> 
             <freeBalance> 30 </freeBalance> 
             <reservedBalance> 20 </reservedBalance> 
             ... 
           </account> 
         </accounts> 
endmodule 
```

However, if I remove the surrounding `<accounts>`, it no longer works, because it wants to show taht the `AccountCellMap` is well defined. I'll open a new issue for that.
