### ISSUE TITLE
Unevaluated function of List and Map

### ISSUE THREAD

**Issue by nishantjr** [kframework/kore#1721]
When the following error occurs, it is difficult to figure out which rule caused the issue.

```
Failed substitution coverage check!
The substitution (above, in the unifier) did not cover the axiom variables:
    VarX:SortId{}
in the left-hand side of the axiom.
CallStack (from HasCallStack):
```

**Comment by ttuegel** [comment]
Please provide the entire error message. This is an internal error, there is nothing you can do about it.

**Comment by nishantjr** [comment]
https://gist.github.com/nishantjr/f2a69058a6635173645e41bcdd175895

**Comment by ttuegel** [comment]
What does `kore-exec --version` report?

**Comment by nishantjr** [comment]
```
Kore version 0.0.1.0
Git:
  revision:	bc4cd5ded05e1a3dbeb744027818d326f69f5f68
  branch:	HEAD
  last commit:	2020 Mar 20 07:24:55 -0500
Build date:	2020 Apr 01 23:50:49 +0530
```

**Comment by ttuegel** [comment]
I think you are seeing a function evaluation issue that is fixed in a newer version of Kore, which should be available in a newer K Framework release.

**Comment by nishantjr** [comment]
OK. I'm still seeing this on the branch `origin/_update-deps_haskell-backend_src_main_native_haskell-backend`

https://gist.github.com/nishantjr/4a9bd4570e07f5330d6f4ab67a2d6634

**Comment by ttuegel** [comment]
>  I'm still seeing this on the branch

That's a completely different instance of the "substitution coverage" error. I'm concerned by the un-evaluated `lookupMember` function, but that also doesn't seem to be related to the missing `VarHOLE` variable. Could you please post the rules you are using for `_(_)` and `lookupMember`?

**Comment by ttuegel** [comment]
@traiansf I wonder if this issue is related to [`Kore.Builtin.renormalize`](https://github.com/kframework/kore/blob/master/kore/src/Kore/Builtin.hs#L209) not being recursive, as you pointed out...

**Comment by ttuegel** [comment]
@nishantjr Could you please post instructions to reproduce this issue?

**Comment by traiansf** [comment]
I've managed to make some progress and reached a List/Map-related error:
```
cat tests/factorial.kool.in 2>/dev/null | /home/traian/Documents/k/k-distribution/bin/krun ../programs/factorial.kool --haskell-backend-command /home/traian/Documents/kore/.build/kore/bin/kore-exec   -d . | diff - tests/factorial.kool.out
kore-exec: [2020-04-24 12:00:21.335430893] Error (ErrorException):
    Map and Set may only contain constructor-like keys (resp. elements).
      Simplifiable keys:
        /* Created: Kore.Step.Simplification.AndTerms.equalInjectiveHeadsAndEquals */
        /* Fl Fn D Sfc */
        Lbl'-LT-'thread'-GT-'{}(
            /* Created: Kore.Step.Simplification.AndTerms.equalInjectiveHeadsAndEquals */
            /* Fl Fn D Sfc */
            Lbl'-LT-'k'-GT-'{}(
                /* Created: Kore.Step.Simplification.AndTerms.equalInjectiveHeadsAndEquals */
                /* Fl Fn D Sfc */
                kseq{}(
                    /* Fl Fn D Spc */
                    /* Inj: */ inj{SortDecl{}, SortKItem{}}(
                        /* Created: Kore.Step.Simplification.AndTerms.equalInjectiveHeadsAndEquals */
                        /* Fl Fn D Sfc */
                        Lblclass'UndsUndsUnds'KOOL-TYPED-DYNAMIC-SYNTAX'Unds'Decl'Unds'Id'Unds'Block{}(
                            /* Fl Fn D Sfa Cl */
                            \dv{SortId{}}(/* Fl Fn D Sfa Cl */ "Main"),
                            /* Fl Fn D Sfc */
                            Lbl'LBraUndsRBraUnds'KOOL-TYPED-DYNAMIC-SYNTAX'Unds'Block'Unds'Stmts{}(
                                /* Fl Fn D Sfc */
                                Lbl'UndsUndsUnds'KOOL-TYPED-DYNAMIC-SYNTAX'Unds'Stmts'Unds'Stmts'Unds'Stmts{}(
                                    /* Fl Fn D Sfc */
                                    /* Inj: */ inj{SortDecl{}, SortStmts{}}(
                                        /* Fl Fn D Sfc */
                                        Lbl'UndsUndsLParUndsRParUndsUnds'KOOL-TYPED-DYNAMIC-SYNTAX'Unds'Decl'Unds'Type'Unds'Id'Unds'Params'Unds'Block{}(
                                            /* Fl Fn D Sfa Cl */
                                            Lblint'Unds'KOOL-TYPED-DYNAMIC-SYNTAX'Unds'Type{}(),
                                            /* Fl Fn D Sfa Cl */
                                            \dv{SortId{}}(/* Fl Fn D Sfa Cl */ "f"),
                                            /* Fl Fn D Sfa Cl */
                                            Lbl'UndsCommUndsUnds'KOOL-TYPED-DYNAMIC-SYNTAX'Unds'Params'Unds'Param'Unds'Params{}(
                                                /* Fl Fn D Sfa Cl */
                                                Lbl'UndsUndsUnds'KOOL-TYPED-DYNAMIC-SYNTAX'Unds'Param'Unds'Type'Unds'Id{}(
                                                    /* Fl Fn D Sfa Cl */
                                                    Lblint'Unds'KOOL-TYPED-DYNAMIC-SYNTAX'Unds'Type{}(),
                                                    /* Fl Fn D Sfa Cl */
                                                    \dv{SortId{}}(/* Fl Fn D Sfa Cl */
                                                    "x")
                                                ),
                                                /* Fl Fn D Sfa Cl */
                                                Lbl'Stop'List'LBraQuotUndsCommUndsUnds'KOOL-TYPED-DYNAMIC-SYNTAX'Unds'Params'Unds'Param'Unds'Params'QuotRBraUnds'Params{}()
                                            ),
                                            /* Fl Fn D Sfc */
                                            Lbl'LBraUndsRBraUnds'KOOL-TYPED-DYNAMIC-SYNTAX'Unds'Block'Unds'Stmts{}(
                                                /* Fl Fn D Sfc */
                                                /* Inj: */ inj{SortStmt{}, SortStmts{}}(
                                                    /* Fl Fn D Sfc */
                                                    Lblif'LParUndsRParUnds'else'UndsUnds'KOOL-TYPED-DYNAMIC-SYNTAX'Unds'Stmt'Unds'Exp'Unds'Block'Unds'Block{}(
                                                        /* Fl Fn D Sfa Cl */
                                                        Lbl'Unds-LT-EqlsUndsUnds'KOOL-TYPED-DYNAMIC-SYNTAX'Unds'Exp'Unds'Exp'Unds'Exp{}(
                                                            /* Fl Fn D Sfa Cli */
                                                            /* Inj: */ inj{SortId{}, SortExp{}}(
                                                                /* Fl Fn D Sfa Cl */
                                                                \dv{SortId{}}(/* Fl Fn D Sfa Cl */
                                                                "x")
                                                            ),
                                                            /* Fl Fn D Sfa Cli */
                                                            /* Inj: */ inj{SortInt{}, SortExp{}}(
                                                                /* Fl Fn D Sfa Cl */
                                                                /* builtin: */
                                                                \dv{SortInt{}}("1")
                                                            )
                                                        ),
                                                        /* Fl Fn D Sfa Cl */
                                                        Lbl'LBraUndsRBraUnds'KOOL-TYPED-DYNAMIC-SYNTAX'Unds'Block'Unds'Stmts{}(
                                                            /* Fl Fn D Sfa Cli */
                                                            /* Inj: */ inj{SortStmt{}, SortStmts{}}(
                                                                /* Fl Fn D Sfa Cl */
                                                                Lblreturn'UndsSClnUnds'KOOL-TYPED-DYNAMIC-SYNTAX'Unds'Stmt'Unds'Exp{}(
                                                                    /* Fl Fn D Sfa Cli */
                                                                    /* Inj: */ inj{SortInt{}, SortExp{}}(
                                                                        /* Fl Fn D Sfa Cl */
                                                                        /* builtin: */
                                                                        \dv{SortInt{}}("1")
                                                                    )
                                                                )
                                                            )
                                                        ),
                                                        /* Fl Fn D Sfc */
                                                        Lbl'LBraUndsRBraUnds'KOOL-TYPED-DYNAMIC-SYNTAX'Unds'Block'Unds'Stmts{}(
                                                            /* Fl Fn D Sfc */
                                                            /* Inj: */ inj{SortStmt{}, SortStmts{}}(
                                                                /* Fl Fn D Sfa */
                                                                Lblreturn'UndsSClnUnds'KOOL-TYPED-DYNAMIC-SYNTAX'Unds'Stmt'Unds'Exp{}(
                                                                    /* Fl Fn D Sfa */
                                                                    Lbl'UndsStarUndsUnds'KOOL-TYPED-DYNAMIC-SYNTAX'Unds'Exp'Unds'Exp'Unds'Exp{}(
                                                                        /* Fl Fn D Sfa Cli */
                                                                        /* Inj: */ inj{SortId{}, SortExp{}}(
                                                                            /* Fl Fn D Sfa Cl */
                                                                            \dv{SortId{}}(/* Fl Fn D Sfa Cl */
                                                                            "x")
                                                                        ),
                                                                        /* Fl Fn D Sfa */
                                                                        Lbl'UndsLParUndsRParUnds'KOOL-TYPED-DYNAMIC-SYNTAX'Unds'Exp'Unds'Exp'Unds'Exps{}(
                                                                            /* Fl Fn D Sfa Cli */
                                                                            /* Inj: */ inj{SortId{}, SortExp{}}(
                                                                                /* Fl Fn D Sfa Cl */
                                                                                \dv{SortId{}}(/* Fl Fn D Sfa Cl */
                                                                                "f")
                                                                            ),
                                                                            /* Fl Fn D Sfa */
                                                                            Lbl'UndsCommUndsUnds'KOOL-TYPED-DYNAMIC-SYNTAX'Unds'Exps'Unds'Exp'Unds'Exps{}(
                                                                                /* Fl Fn D Sfa Cl */
                                                                                Lbl'Unds'-'UndsUnds'KOOL-TYPED-DYNAMIC-SYNTAX'Unds'Exp'Unds'Exp'Unds'Exp{}(
                                                                                    /* Fl Fn D Sfa Cli */
                                                                                    /* Inj: */ inj{SortId{}, SortExp{}}(
                                                                                        /* Fl Fn D Sfa Cl */
                                                                                        \dv{SortId{}}(/* Fl Fn D Sfa Cl */
                                                                                        "x")
                                                                                    ),
                                                                                    /* Fl Fn D Sfa Cli */
                                                                                    /* Inj: */ inj{SortInt{}, SortExp{}}(
                                                                                        /* Fl Fn D Sfa Cl */
                                                                                        /* builtin: */
                                                                                        \dv{SortInt{}}("1")
                                                                                    )
                                                                                ),
                                                                                /* Fl Fn D Sfa Cli */
                                                                                /* Inj: */ inj{SortVals{}, SortExps{}}(
                                                                                    /* Fl Fn D Sfa Cl */
                                                                                    Lbl'Stop'List'LBraQuotUndsCommUndsUnds'KOOL-TYPED-DYNAMIC-SYNTAX'Unds'Vals'Unds'Val'Unds'Vals'QuotRBraUnds'Vals{}()
                                                                                )
                                                                            )
                                                                        )
                                                                    )
                                                                )
                                                            )
                                                        )
                                                    )
                                                )
                                            )
                                        )
                                    ),
                                    /* Fl Fn D Sfc */
                                    /* Inj: */ inj{SortDecl{}, SortStmts{}}(
                                        /* Fl Fn D Sfc */
                                        Lbl'UndsUndsLParUndsRParUndsUnds'KOOL-TYPED-DYNAMIC-SYNTAX'Unds'Decl'Unds'Type'Unds'Id'Unds'Params'Unds'Block{}(
                                            /* Fl Fn D Sfa Cl */
                                            Lblvoid'Unds'KOOL-TYPED-DYNAMIC-SYNTAX'Unds'Type{}(),
                                            /* Fl Fn D Sfa Cl */
                                            \dv{SortId{}}(/* Fl Fn D Sfa Cl */
                                            "Main"),
                                            /* Fl Fn D Sfa Cl */
                                            Lbl'Stop'List'LBraQuotUndsCommUndsUnds'KOOL-TYPED-DYNAMIC-SYNTAX'Unds'Params'Unds'Param'Unds'Params'QuotRBraUnds'Params{}(),
                                            /* Fl Fn D Sfc */
                                            Lbl'LBraUndsRBraUnds'KOOL-TYPED-DYNAMIC-SYNTAX'Unds'Block'Unds'Stmts{}(
                                                /* Fl Fn D Sfc */
                                                /* Inj: */ inj{SortStmt{}, SortStmts{}}(
                                                    /* Fl Fn D Sfa */
                                                    Lblprint'LParUndsRParSClnUnds'KOOL-TYPED-DYNAMIC-SYNTAX'Unds'Stmt'Unds'Exps{}(
                                                        /* Fl Fn D Sfa */
                                                        Lbl'UndsCommUndsUnds'KOOL-TYPED-DYNAMIC-SYNTAX'Unds'Exps'Unds'Exp'Unds'Exps{}(
                                                            /* Fl Fn D Sfa */
                                                            Lbl'UndsLParUndsRParUnds'KOOL-TYPED-DYNAMIC-SYNTAX'Unds'Exp'Unds'Exp'Unds'Exps{}(
                                                                /* Fl Fn D Sfa Cli */
                                                                /* Inj: */ inj{SortId{}, SortExp{}}(
                                                                    /* Fl Fn D Sfa Cl */
                                                                    \dv{SortId{}}(/* Fl Fn D Sfa Cl */
                                                                    "f")
                                                                ),
                                                                /* Fl Fn D Sfa */
                                                                Lbl'UndsCommUndsUnds'KOOL-TYPED-DYNAMIC-SYNTAX'Unds'Exps'Unds'Exp'Unds'Exps{}(
                                                                    /* Fl Fn D Sfa Cl */
                                                                    Lbl'UndsLParUndsRParUnds'KOOL-TYPED-DYNAMIC-SYNTAX'Unds'Exp'Unds'Exp'Unds'Exps{}(
                                                                        /* Fl Fn D Sfa Cli */
                                                                        /* Inj: */ inj{SortId{}, SortExp{}}(
                                                                            /* Fl Fn D Sfa Cl */
                                                                            \dv{SortId{}}(/* Fl Fn D Sfa Cl */
                                                                            "f")
                                                                        ),
                                                                        /* Fl Fn D Sfa Cli */
                                                                        /* Inj: */ inj{SortVals{}, SortExps{}}(
                                                                            /* Fl Fn D Sfa Cl */
                                                                            Lbl'UndsCommUndsUnds'KOOL-TYPED-DYNAMIC-SYNTAX'Unds'Vals'Unds'Val'Unds'Vals{}(
                                                                                /* Fl Fn D Sfa Cli */
                                                                                /* Inj: */ inj{SortInt{}, SortVal{}}(
                                                                                    /* Fl Fn D Sfa Cl */
                                                                                    /* builtin: */
                                                                                    \dv{SortInt{}}("5")
                                                                                ),
                                                                                /* Fl Fn D Sfa Cl */
                                                                                Lbl'Stop'List'LBraQuotUndsCommUndsUnds'KOOL-TYPED-DYNAMIC-SYNTAX'Unds'Vals'Unds'Val'Unds'Vals'QuotRBraUnds'Vals{}()
                                                                            )
                                                                        )
                                                                    ),
                                                                    /* Fl Fn D Sfa Cli */
                                                                    /* Inj: */ inj{SortVals{}, SortExps{}}(
                                                                        /* Fl Fn D Sfa Cl */
                                                                        Lbl'Stop'List'LBraQuotUndsCommUndsUnds'KOOL-TYPED-DYNAMIC-SYNTAX'Unds'Vals'Unds'Val'Unds'Vals'QuotRBraUnds'Vals{}()
                                                                    )
                                                                )
                                                            ),
                                                            /* Fl Fn D Sfa Cli */
                                                            /* Inj: */ inj{SortVals{}, SortExps{}}(
                                                                /* Fl Fn D Sfa Cl */
                                                                Lbl'UndsCommUndsUnds'KOOL-TYPED-DYNAMIC-SYNTAX'Unds'Vals'Unds'Val'Unds'Vals{}(
                                                                    /* Fl Fn D Sfa Cli */
                                                                    /* Inj: */ inj{SortString{}, SortVal{}}(
                                                                        /* Fl Fn D Sfa Cl */
                                                                        /* builtin: */
                                                                        \dv{SortString{}}("\x0a")
                                                                    ),
                                                                    /* Fl Fn D Sfa Cl */
                                                                    Lbl'Stop'List'LBraQuotUndsCommUndsUnds'KOOL-TYPED-DYNAMIC-SYNTAX'Unds'Vals'Unds'Val'Unds'Vals'QuotRBraUnds'Vals{}()
                                                                )
                                                            )
                                                        )
                                                    )
                                                )
                                            )
                                        )
                                    )
                                )
                            )
                        )
                    ),
                    /* Fl Fn D Sfa Cl */
                    kseq{}(
                        /* Fl Fn D Sfa Cl */
                        Lblexecute'Unds'KOOL-TYPED-DYNAMIC'Unds'KItem{}(),
                        /* Fl Fn D Sfa Cl */ dotk{}()
                    )
                )
            ),
            /* Fl Fn D Sfa */
            Lbl'-LT-'control'-GT-'{}(
                /* Fl Fn D Sfa */
                Lbl'-LT-'fstack'-GT-'{}(
                    /* Fl Fn D Sfa */ /* builtin: */ Lbl'Stop'List{}()
                ),
                /* Fl Fn D Sfa */
                Lbl'-LT-'xstack'-GT-'{}(
                    /* Fl Fn D Sfa */ /* builtin: */ Lbl'Stop'List{}()
                ),
                /* Fl Fn D Sfa Cl */
                Lbl'-LT-'returnType'-GT-'{}(
                    /* Fl Fn D Sfa Cl */
                    Lblvoid'Unds'KOOL-TYPED-DYNAMIC-SYNTAX'Unds'Type{}()
                ),
                /* Fl Fn D Sfa */
                Lbl'-LT-'crntObj'-GT-'{}(
                    /* Fl Fn D Sfa Cl */
                    Lbl'-LT-'crntClass'-GT-'{}(
                        /* Fl Fn D Sfa Cl */
                        \dv{SortId{}}(/* Fl Fn D Sfa Cl */ "Object")
                    ),
                    /* Fl Fn D Sfa */
                    Lbl'-LT-'envStack'-GT-'{}(
                        /* Fl Fn D Sfa */ /* builtin: */ Lbl'Stop'List{}()
                    ),
                    /* Fl Fn D Sfa Cl */ Lbl'Stop'LocationCell{}()
                )
            ),
            /* Fl Fn D Sfa Cl */
            Lbl'-LT-'env'-GT-'{}(
                /* Fl Fn D Sfa Cl */ /* builtin: */ Lbl'Stop'Map{}()
            ),
            /* Fl Fn D Sfa Cl */
            Lbl'-LT-'holds'-GT-'{}(
                /* Fl Fn D Sfa Cl */ /* builtin: */ Lbl'Stop'Map{}()
            ),
            /* Fl Fn D Sfa Cl */
            Lbl'-LT-'id'-GT-'{}(
                /* Fl Fn D Sfa Cl */ /* builtin: */ \dv{SortInt{}}("0")
            )
        )
    CallStack (from HasCallStack):
      error, called at src/Kore/Internal/TermLike.hs:433:14 in kore-0.0.1.0-CBEox1KiyLiCkv3JNMv5A5:Kore.Internal.TermLike
[Error] Critical: Haskell Backend execution failed with code 1 and produced no
output.
```

**Comment by nishantjr** [comment]
@ttuegel sorry for the delay.

Checkout the `kool-haskell` branch of the K repo
and run `cd k-distribution/tutorial/2_languages/2_kool/2_typed/1_dynamic; make`

The particular program that I saw the error with is `programs/cast-1.kool` but I suspect all programs will fail.

**Comment by traiansf** [comment]
OK. I found one issue.  KOOL contains two anywhere rules involving constructors,
```
  rule V:Val[N1:Int, N2:Int, Vs:Vals] => V[N1][N2, Vs]
    [structural, anywhere]

  rule array(_:Type, L:Int, M:Int)[N:Int] => lookup(L +Int N)
    requires N >=Int 0 andBool N <Int M  [structural, anywhere]
```

Because of these rules, the array dereferencing operation `_[_]` is no longer considered a constructor. However, since our unification procedure expects LHSs to be constructor-based, we get the substitution coverage error.

As a temporary fix, I commented out these rules, which means `_[_]` is again a constructor; with this change, the factorial program seems to pass that point, but then slowly (16 CPU mins) eats up the entire memory (16GB) and crashes (OOM).

Running `cast-1.kool` it manages to finish, but it seems to gather additional constraints:
```
  <T>
    <threads>
      .ThreadCellMap
    </threads>
    <store>
      0 |-> objectClosure ( Main , ListItem ( envStackFrame ( Main , Main |-> 1 ) )
      ListItem ( envStackFrame ( Object , .Map ) ) )
      1 |-> methodClosure ( void , .Types -> void , Main , 0 , .Params , { ( B b , .Vals ; b = new B ( .Vals ) ; ) ( A a , .Vals ; a = ( A ) b ; ) print ( "b.x = " , b . x , "\n" , .Vals ) ; print ( "a.x = " , a . x , "\n" , .Vals ) ; print ( "a.getB() = " , a . getB ( .Vals ) , "\n" , .Vals ) ; print ( "a.getA() = " , a . getA ( .Vals ) , "\n" , .Vals ) ; } )
      2 |-> objectClosure ( B , ListItem ( envStackFrame ( B , B |-> 8
      getB |-> 9
      x |-> 7 ) )
      ListItem ( envStackFrame ( A , A |-> 5
      getA |-> 6
      x |-> 4 ) )
      ListItem ( envStackFrame ( Object , .Map ) ) )
      3 |-> objectClosure ( B , ListItem ( envStackFrame ( B , B |-> 8
      getB |-> 9
      x |-> 7 ) )
      ListItem ( envStackFrame ( A , A |-> 5
      getA |-> 6
      x |-> 4 ) )
      ListItem ( envStackFrame ( Object , .Map ) ) )
      4 |-> 10
      5 |-> methodClosure ( void , .Types -> void , A , 3 , .Params , { x = 10 ; } )
      6 |-> methodClosure ( void , .Types -> int , A , 3 , .Params , { return x ; } )
      7 |-> 20
      8 |-> methodClosure ( void , .Types -> void , B , 3 , .Params , { super . A ( .Vals ) ; x = 20 ; } )
      9 |-> methodClosure ( void , .Types -> int , B , 3 , .Params , { return x ; } )
      10 |-> objectClosure ( A , ListItem ( envStackFrame ( B , B |-> 8
      getB |-> 9
      x |-> 7 ) )
      ListItem ( envStackFrame ( A , A |-> 5
      getA |-> 6
      x |-> 4 ) )
      ListItem ( envStackFrame ( Object , .Map ) ) )
    </store>
    <busy>
      .Set
    </busy>
    <terminated>
      SetItem ( 0 )
    </terminated>
    <input>
      .List
    </input>
    <output>
      ListItem ( "b.x = " )
      ListItem ( 20 )
      ListItem ( "\n" )
      ListItem ( "a.x = " )
      ListItem ( 10 )
      ListItem ( "\n" )
      ListItem ( "a.getB() = " )
      ListItem ( 20 )
      ListItem ( "\n" )
      ListItem ( "a.getA() = " )
      ListItem ( 10 )
      ListItem ( "\n" )
    </output>
    <nextLoc>
      11
    </nextLoc>
    <classes>
      <classData>
        <className>
          A
        </className>
        <baseClass>
          Object
        </baseClass>
        <declarations>
          int x , .Vals ; void A ( .Params ) { x = 10 ; } int getA ( .Params ) { return x ; }
        </declarations>
      </classData> <classData>
        <className>
          B
        </className>
        <baseClass>
          A
        </baseClass>
        <declarations>
          int x , .Vals ; void B ( .Params ) { super . A ( .Vals ) ; x = 20 ; } int getB ( .Params ) { return x ; }
        </declarations>
      </classData> <classData>
        <className>
          Main
        </className>
        <baseClass>
          Object
        </baseClass>
        <declarations>
          void Main ( .Params ) { ( B b , .Vals ; b = new B ( .Vals ) ; ) ( A a , .Vals ; a = ( A ) b ; ) print ( "b.x = " , b . x , "\n" , .Vals ) ; print ( "a.x = " , a . x , "\n" , .Vals ) ; print ( "a.getB() = " , a . getB ( .Vals ) , "\n" , .Vals ) ; print ( "a.getA() = " , a . getA ( .Vals ) , "\n" , .Vals ) ; }
        </declarations>
      </classData>
    </classes>
  </T>
#And
  {
    true
  #Equals
    notBool isKResult ( a . getA ( .Vals ) , "\n" , .Vals )
  }
#And
  {
    true
  #Equals
    notBool isKResult ( a . getB ( .Vals ) , "\n" , .Vals )
  }
#And
  {
    true
  #Equals
    notBool isKResult ( a . x , "\n" , .Vals )
  }
#And
  {
    true
  #Equals
    notBool isKResult ( b . x , "\n" , .Vals )
  }
```

I assume this might be the reason why the memory keeps growing.
